const nodes = {
    "automaticRearrangeAfterDropNode": true,
    "collapsible": false,
    "directed": false,
    "focusAnimationDuration": 0.75,
    "focusZoom": 5,
    "freezeAllDragEvents": false,
    "height": 400,
    "highlightDegree": 1,
    "highlightOpacity": 0.4,
    "linkHighlightBehavior": true,
    "maxZoom": 1,
    "minZoom": 0.1,
    "nodeHighlightBehavior": false,
    "panAndZoom": true,
    "staticGraph": true,
    "staticGraphWithDragAndDrop": true,
    "width": 800,
    "d3": {
        "alphaTarget": 0.05,
        "gravity": -100,
        "linkLength": 100,
        "linkStrength": 1,
        "disableLinkForce": false
    },
    "node": {
        "color": "#d3d3d3",
        "fontColor": "black",
        "fontSize": 14,
        "fontWeight": "normal",
        "highlightColor": "SAME",
        "highlightFontSize": 8,
        "highlightFontWeight": "normal",
        "highlightStrokeColor": "SAME",
        "highlightStrokeWidth": "SAME",
        "labelProperty": "id",
        "mouseCursor": "pointer",
        "opacity": 1,
        "renderLabel": true,
        "size": 200,
        "strokeColor": "none",
        "strokeWidth": 1.5,
        "svg": "",
        "symbolType": "circle"
    },
    "link": {
        "color": "#d3d3d3",
        "fontColor": "black",
        "fontSize": 8,
        "fontWeight": "normal",
        "highlightColor": "SAME",
        "highlightFontSize": 8,
        "highlightFontWeight": "normal",
        "labelProperty": "label",
        "mouseCursor": "pointer",
        "opacity": 1,
        "renderLabel": false,
        "semanticStrokeWidth": false,
        "strokeWidth": 1.5,
        "markerHeight": 6,
        "markerWidth": 6,
        "strokeDasharray": 0,
        "strokeDashoffset": 0,
        "strokeLinecap": "butt"
    }
}


export default nodes
